// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: api/proto/metadata.proto

package metadata

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FilesMetadataResponse struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Files         []*FileMetadataResponse `protobuf:"bytes,1,rep,name=files,proto3" json:"files,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FilesMetadataResponse) Reset() {
	*x = FilesMetadataResponse{}
	mi := &file_api_proto_metadata_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FilesMetadataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FilesMetadataResponse) ProtoMessage() {}

func (x *FilesMetadataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_metadata_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FilesMetadataResponse.ProtoReflect.Descriptor instead.
func (*FilesMetadataResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_metadata_proto_rawDescGZIP(), []int{0}
}

func (x *FilesMetadataResponse) GetFiles() []*FileMetadataResponse {
	if x != nil {
		return x.Files
	}
	return nil
}

type FileMetadataResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Url           string                 `protobuf:"bytes,3,opt,name=url,proto3" json:"url,omitempty"`
	Size          int64                  `protobuf:"varint,4,opt,name=size,proto3" json:"size,omitempty"`
	Type          string                 `protobuf:"bytes,5,opt,name=type,proto3" json:"type,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,6,opt,name=CreatedAt,proto3" json:"CreatedAt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileMetadataResponse) Reset() {
	*x = FileMetadataResponse{}
	mi := &file_api_proto_metadata_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileMetadataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileMetadataResponse) ProtoMessage() {}

func (x *FileMetadataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_metadata_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileMetadataResponse.ProtoReflect.Descriptor instead.
func (*FileMetadataResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_metadata_proto_rawDescGZIP(), []int{1}
}

func (x *FileMetadataResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *FileMetadataResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *FileMetadataResponse) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *FileMetadataResponse) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *FileMetadataResponse) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *FileMetadataResponse) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

type FileMetadataRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileMetadataRequest) Reset() {
	*x = FileMetadataRequest{}
	mi := &file_api_proto_metadata_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileMetadataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileMetadataRequest) ProtoMessage() {}

func (x *FileMetadataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_metadata_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileMetadataRequest.ProtoReflect.Descriptor instead.
func (*FileMetadataRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_metadata_proto_rawDescGZIP(), []int{2}
}

func (x *FileMetadataRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

var File_api_proto_metadata_proto protoreflect.FileDescriptor

const file_api_proto_metadata_proto_rawDesc = "" +
	"\n" +
	"\x18api/proto/metadata.proto\x12\ametadta\x1a\x1bgoogle/protobuf/empty.proto\"L\n" +
	"\x15FilesMetadataResponse\x123\n" +
	"\x05files\x18\x01 \x03(\v2\x1d.metadta.FileMetadataResponseR\x05files\"\x92\x01\n" +
	"\x14FileMetadataResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x10\n" +
	"\x03url\x18\x03 \x01(\tR\x03url\x12\x12\n" +
	"\x04size\x18\x04 \x01(\x03R\x04size\x12\x12\n" +
	"\x04type\x18\x05 \x01(\tR\x04type\x12\x1c\n" +
	"\tCreatedAt\x18\x06 \x01(\tR\tCreatedAt\"%\n" +
	"\x13FileMetadataRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id2\x9b\x01\n" +
	"\x0fMetadataService\x12@\n" +
	"\x06GetAll\x12\x16.google.protobuf.Empty\x1a\x1e.metadta.FilesMetadataResponse\x12F\n" +
	"\aGetById\x12\x1c.metadta.FileMetadataRequest\x1a\x1d.metadta.FileMetadataResponseB\x19Z\x17/grpc/metadata;metadatab\x06proto3"

var (
	file_api_proto_metadata_proto_rawDescOnce sync.Once
	file_api_proto_metadata_proto_rawDescData []byte
)

func file_api_proto_metadata_proto_rawDescGZIP() []byte {
	file_api_proto_metadata_proto_rawDescOnce.Do(func() {
		file_api_proto_metadata_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_metadata_proto_rawDesc), len(file_api_proto_metadata_proto_rawDesc)))
	})
	return file_api_proto_metadata_proto_rawDescData
}

var file_api_proto_metadata_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_api_proto_metadata_proto_goTypes = []any{
	(*FilesMetadataResponse)(nil), // 0: metadta.FilesMetadataResponse
	(*FileMetadataResponse)(nil),  // 1: metadta.FileMetadataResponse
	(*FileMetadataRequest)(nil),   // 2: metadta.FileMetadataRequest
	(*emptypb.Empty)(nil),         // 3: google.protobuf.Empty
}
var file_api_proto_metadata_proto_depIdxs = []int32{
	1, // 0: metadta.FilesMetadataResponse.files:type_name -> metadta.FileMetadataResponse
	3, // 1: metadta.MetadataService.GetAll:input_type -> google.protobuf.Empty
	2, // 2: metadta.MetadataService.GetById:input_type -> metadta.FileMetadataRequest
	0, // 3: metadta.MetadataService.GetAll:output_type -> metadta.FilesMetadataResponse
	1, // 4: metadta.MetadataService.GetById:output_type -> metadta.FileMetadataResponse
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_api_proto_metadata_proto_init() }
func file_api_proto_metadata_proto_init() {
	if File_api_proto_metadata_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_metadata_proto_rawDesc), len(file_api_proto_metadata_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_metadata_proto_goTypes,
		DependencyIndexes: file_api_proto_metadata_proto_depIdxs,
		MessageInfos:      file_api_proto_metadata_proto_msgTypes,
	}.Build()
	File_api_proto_metadata_proto = out.File
	file_api_proto_metadata_proto_goTypes = nil
	file_api_proto_metadata_proto_depIdxs = nil
}
