FROM golang:1.25 AS builder

WORKDIR /build

RUN apt-get update && apt-get install -y librdkafka-dev

COPY go.mod go.sum ./
RUN go mod download

COPY . .

ENV CGO_ENABLED=1

RUN go build -o ./metadata_service ./cmd/metadata_service/main.go

FROM gcr.io/distroless/base-debian12

WORKDIR /app

COPY --from=builder /build/metadata_service ./metadata_service

COPY ./config ./config

CMD [ "/app/metadata_service" ]

