FROM golang:1.25 AS builder

WORKDIR /build

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN go build -o ./gateway ./cmd/gateway/main.go

FROM gcr.io/distroless/base-debian12

WORKDIR /app

COPY --from=builder /build/gateway ./gateway

COPY ./config ./config

COPY ./api/rest/ ./api/rest/

CMD [ "/app/gateway" ]

