apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yaml -o k8s/
    kompose.version: 1.37.0 (fb0539e64)
  labels:
    io.kompose.service: gateway
  name: gateway
spec:
  ports:
    - name: "gateway"
      port: 8080
      targetPort: 8080
  selector:
    io.kompose.service: gateway
  type: LoadBalancer
