server:
  host: 127.0.0.1
  port: 8080
postgres:
  host: 127.0.0.1
  port: 5432
  user: admin
  password: 1234
  database: test
logger:
  env: local
minio:
  endpoint: localhost:9000
  user: admin123
  password: admin123
  usessl: false
  bucket: "vedro"

  