server:
  host: 127.0.0.1
  port: 8080
postgres:
  host: postgres
  port: 5432
  user: admin
  password: 1234
  database: storage
logger:
  env: dev
minio:
  endpoint: minio:9000
  user: admin123
  password: admin123
  usessl: false
  bucket: "vedro"
kafka:
  host: kafka:9092
  group: metadata-group
  timeout: 10000
  autocommit: true
  offsetstore: false
  commitinterval: 10000
  topic: metadata-topic
file:
  host: file_service
  port: 50051
metadata:
  host: metadata_service
  port: 50052

  