# apiVersion: apps/v1
# kind: StatefulSet
# metadata:
#   name: postgres
# spec:
#   serviceName: postgres
#   replicas: 1
#   selector:
#     matchLabels:
#       app: postgres
#   template:
#     metadata:
#       labels:
#         app: postgres
#     spec:
#       containers:
#         - name: postgres
#           image: postgres:alpine
#           env:
#             - name: POSTGRES_DB
#               value: storage
#             - name: POSTGRES_PASSWORD
#               value: "1234"
#             - name: POSTGRES_USER
#               value: admin
#           ports:
#             - containerPort: 5432
#           readinessProbe:
#             exec:
#               command: ["pg_isready", "-U", "admin"]
#             initialDelaySeconds: 5
#             periodSeconds: 5
#           volumeMounts:
#             - name: data
#               mountPath: /var/lib/postgresql/data
#   volumeClaimTemplates:
#     - metadata:
#         name: data
#       spec:
#         accessModes: ["ReadWriteOnce"]
#         resources:
#           requests:
#             storage: 1Gi

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
spec:
  selector:
    matchLabels:
      app: postgres
  serviceName: postgres
  replicas: 1
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres:alpine
        env:
          - name: POSTGRES_DB
            value: storage
          - name: POSTGRES_PASSWORD
            value: "1234"
          - name: POSTGRES_USER
            value: admin
        ports:
        - containerPort: 5432
          name: postgres
        readinessProbe:
          exec:
            command: ["pg_isready", "-U", "admin"]
          initialDelaySeconds: 5
          periodSeconds: 5
        livenessProbe:
          exec:
            command: ["pg_isready", "-U", "admin"]
          initialDelaySeconds: 5
          periodSeconds: 5
        volumeMounts:
        - name: postgres-data
          mountPath: /temp/postgres/data
  volumeClaimTemplates:
  - metadata:
      name: postgres-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi

