apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-data
  namespace: storage-system
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /var/lib/postgresql/data
