apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yaml -o k8s/
    kompose.version: 1.37.0 (fb0539e64)
  labels:
    io.kompose.service: file-service
  name: file-service
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: file-service
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yaml -o k8s/
        kompose.version: 1.37.0 (fb0539e64)
      labels:
        io.kompose.service: file-service
    spec:
      containers:
        - env:
            - name: APP_ENV
              value: dev
          image: file-service
          imagePullPolicy: Never 
          
          name: file-service
          ports:
            - containerPort: 50051
              protocol: TCP
      restartPolicy: Always
